[profile.default]
src = 'contracts'
test = 'test/foundry/'
out = 'out'
optimizer = true
optimizer_runs = 1_000
ffi=true

libs = [
  'lib',
  'node_modules/@openzeppelin',
  'node_modules/hardhat',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = '0.8.22'
use_literal_content = true
extra_output = ["devdoc", "userdoc", "storagelayout"]
evm_version = 'istanbul'
cache_path = 'cache_foundry'
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true

[profile.ci]
verbosity = 4

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[profile.via-ir.fuzz]
runs = 1_000

[profile.min-solc]
solc_version = "0.8.4"

[profile.min-solc.fuzz]
runs = 1_000

[profile.min-solc-via-ir.fuzz]
runs = 1_000

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-mainnet = "https://api-archived.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
ronin-devnet = "https://hcm-rpc.skymavis.one/rpc"
localhost = "http://localhost:8545"
ronin-testnet-shadow = "http://34.27.172.168:8545"
ronin-mainnet-shadow = "http://35.225.161.81:8545"